// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJKZbuSaIxuPW__NGVzChOh5c9zfnn48',
    appId: '1:1044896602037:web:99d19677b5abb30c8d2bfc',
    messagingSenderId: '1044896602037',
    projectId: 'transfer-web-370010',
    authDomain: 'transfer-web-370010.firebaseapp.com',
    storageBucket: 'transfer-web-370010.appspot.com',
    measurementId: 'G-DRHVSMEDR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdz61hizHw1JVussQB3SsHUECc3Ptow2I',
    appId: '1:1044896602037:android:bf1980f45e4b2f978d2bfc',
    messagingSenderId: '1044896602037',
    projectId: 'transfer-web-370010',
    storageBucket: 'transfer-web-370010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY81OtQA2knl-d3LaWsQVgqdOUqIXxl8o',
    appId: '1:1044896602037:ios:6ed2c32462053a998d2bfc',
    messagingSenderId: '1044896602037',
    projectId: 'transfer-web-370010',
    storageBucket: 'transfer-web-370010.appspot.com',
    iosBundleId: 'com.example.apForInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY81OtQA2knl-d3LaWsQVgqdOUqIXxl8o',
    appId: '1:1044896602037:ios:887df75fa0ec83b68d2bfc',
    messagingSenderId: '1044896602037',
    projectId: 'transfer-web-370010',
    storageBucket: 'transfer-web-370010.appspot.com',
    iosBundleId: 'com.example.apForInterview.RunnerTests',
  );
}
